#! /bin/bash
### BEGIN INIT INFO
# Provides:          cstbox-webadmin
# Required-Start:    $remote_fs $syslog cstbox-dbus
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: CSTBox Administration Web app
# Description:       CSTBox Administration Web app
### END INIT INFO

# This file is part of CSTBox.
#
# CSTBox is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CSTBox is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with CSTBox.  If not, see <http://www.gnu.org/licenses/>.

# Author: Eric Pascual <eric.pascual@cstb.fr>

DESC="CSTBox Administration Webapp"
NAME=cstbox-webadmin
INIT_SEQ=94
CORE_SVC=1
DAEMON=/opt/cstbox/bin/webuid_admin.py
DAEMON_ARGS=
INIT_VERBOSE=yes

. /opt/cstbox/lib/init/init-functions

